{
 "title": "Connectors Self-Managed",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Inbound", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Connector Activations",
   "type": "piechart",
   "description": "Connector activations (i.e. deployments of diagrams that contain inbound connectors) by connector type",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (increase(camunda_connector_inbound_activations_total{action=\"activated\"}[$__range]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Connector Triggers",
   "type": "piechart",
   "description": "Connector invocation by type (e.g. webhook endpoint calls / queue messages consumer / etc.)",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (increase(camunda_connector_inbound_triggers_total{action=\"triggered\"}[$__range]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Connector Triggers Outcomes",
   "type": "piechart",
   "description": "Connector event invocation outcomes",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action) (increase(camunda_connector_inbound_triggers_total{action!=\"triggered\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process definitions checked",
   "type": "stat",
   "description": "Number of process definitions that have been checked for inbound connectors presence within the given time period",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "camunda_connector_inbound_process_definitions_checked_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connectors",
   "type": "stat",
   "description": "Number of connectors that have been active at the end of the selected time period",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "camunda_connector_inbound_activations_total{action=\"activated\"} - on(type) camunda_connector_inbound_activations_total{action=\"deactivated\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Connector Trigger Rate",
   "type": "timeseries",
   "description": "Pattern of connector invocation over time by type, log10 scale",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(type) (increase(camunda_connector_inbound_triggers_total{action=\"triggered\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhook calls duration",
   "type": "timeseries",
   "description": "Average and max durations of the HTTP calls to the inbound webhook connector endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{status!~\"5..\", uri=\"/inbound/{context}\"}[1m])) / sum(rate(http_server_requests_seconds_count{status!~\"5..\", uri=\"/inbound/{context}\"}[1m]))",
     "legendFormat": "Webhook - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{status!~\"5..\", uri=\"/inbound/{context}\"})",
     "legendFormat": "Webhook - MAX"
    }
   ]
  },
  { "title": "Outbound", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Connector Invocations",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (increase(camunda_connector_outbound_invocations_total{action=\"activated\"}[$__range]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Connector Job Outcomes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action) (increase(camunda_connector_outbound_invocations_total{action!=\"activated\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Jobs per Connector",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (increase(camunda_connector_outbound_invocations_total{action=\"failed\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connector Invocation Rate",
   "type": "timeseries",
   "description": "Pattern of connector invocation over time by type, log10 scale",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(type) (increase(camunda_connector_outbound_invocations_total{action=\"activated\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average execution time",
   "type": "stat",
   "description": "Average execution time per connector within the selected timeframe",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(type) (camunda_connector_outbound_execution_time_seconds_sum) / on(type) max by(type) (camunda_connector_outbound_execution_time_seconds_count)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Max execution time",
   "type": "stat",
   "description": "Maximum execution time per connector within the selected timeframe",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "camunda_connector_outbound_execution_time_seconds_max",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "JVM insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by(level) (increase(logback_events_total[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Job executor thread pool",
   "type": "timeseries",
   "description": "Zeebe client job executor thread pool state",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "max_over_time(executor_active_threads{name=\"zeebe_client_thread_pool\"}[$__interval])",
     "legendFormat": "Active threads"
    },
    {
     "expr": "executor_pool_size_threads{name=\"zeebe_client_thread_pool\"}",
     "legendFormat": "Total threads"
    }
   ]
  },
  {
   "title": "Job executor - queued tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "expr": "max_over_time(executor_queued_tasks{name=\"zeebe_client_thread_pool\"}[$__interval])",
     "legendFormat": "Queue size"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\"}) * 100) / sum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"nonheap\"}) * 100) / sum(jvm_memory_max_bytes{area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}